### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nathanbuchholz** [Sceptre/sceptre-json-resolver#7]
Could a license please be added for this?
Thanks!

**Comment by zaro0508** [comment]
is this not enough? https://github.com/Sceptre/sceptre-json-resolver/blob/master/pyproject.toml#L11

![image](https://github.com/Sceptre/sceptre-json-resolver/assets/3697686/ce6ca7cf-33b1-4a07-b182-034e2b73fef9)

**Comment by nathanbuchholz** [comment]
Sorry, I didn't think to look there. That's perfect, thanks!
